service: pets-api

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}

  esbuild:
    platform: "node"
    target: node20
    sourcemap: linked
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs20.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: false
  httpApi:
    cors: false

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 100
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  patterns:
    - "!**/*.test.ts"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
